os: osx
language: objective-c
matrix:
  include:
    - {osx_image: xcode8.3,  env: 'PLAT=iOS  SWFT=3.1  DST="OS=10.3.1,name=iPhone SE"'}

    - {osx_image: xcode9.2,  env: 'PLAT=iOS  SWFT=3.2  DST="OS=11.2,name=iPhone SE"'}

    - {osx_image: xcode9.2,  env: 'PLAT=iOS  SWFT=4.0  DST="OS=8.4,name=iPhone 4s"'}
    - {osx_image: xcode9.2,  env: 'PLAT=iOS  SWFT=4.0  DST="OS=9.3,name=iPhone SE"'}
    - {osx_image: xcode9.2,  env: 'PLAT=iOS  SWFT=4.0  DST="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode9.2,  env: 'PLAT=iOS  SWFT=4.0  DST="OS=11.2,name=iPhone SE"'}
cache:
  directories:
  - Carthage
install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform iOS
script:
  - set -o pipefail
  - xcodebuild -scheme PMKMessagesUI -quiet -destination "$DST" build SWIFT_VERSION=$SWFT
  - xcodebuild -scheme PMKMessagesUI -quiet -destination "$DST" test
